FORMAT: 1A
HOST: https://cryptic-badlands-8184.herokuapp.com/

# Life saving API

# First aid [/rescue]

# Request first aid [POST]

+ Request (application/json)

  + Headers

              Accept: application/json

  + Body
    ```
   {"emergency": "true"}
    ```

+ Response 201 (application/json; charset=utf-8)
  ```
  {"message": "You will live."}
  ```
