FORMAT: 1A
HOST: https://cryptic-badlands-8184.herokuapp.com/

# Life saving API

# First aid [/first_aids]

# Request first aid [POST]

+ Request (application/json)

  + Headers

              Accept: application/json

  + Body
    ```
   {"urgency": "top"}
    ```
+ Response 201 (application/json; charset=utf-8)
  ```
  {"urgency": "top"}
  ```